/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: Creación de Pedido con Token de Autenticación
   Architecture: Monolith Architecture (MVC / Monolithic)
   Stack: typescript + nestjs + prisma
   Generated by gherkin-ai CLI v3.0.0-beta.1
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}



// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const CreacionDePedidoConTokenDeAutenticacionCommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({
    id: z.string()
  })
});

export type CreacionDePedidoConTokenDeAutenticacionCommand = z.infer<typeof CreacionDePedidoConTokenDeAutenticacionCommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface ICreacionDePedidoConTokenDeAutenticacionRepository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
