// Domain kernel for "Creación de Pedido con Token de Autenticación" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

export type CreacionDePedidoConTokenDeAutenticacionState = 'PENDING';
export type CreacionDePedidoConTokenDeAutenticacionEventType = 'ProcessCreacionDePedidoConTokenDeAutenticacionCompleted' | 'CreacionDePedidoConTokenDeAutenticacionProcessed';

export interface CreacionDePedidoConTokenDeAutenticacionDomainEvent {
  type: CreacionDePedidoConTokenDeAutenticacionEventType;
  aggregateId: string;
  version: number;
  occurredOn: Date;
  payload: Record<string, unknown>;
}

export interface CreacionDePedidoConTokenDeAutenticacionCommand {
  /** Identifier of the aggregate the command targets. */
  id: string;
  payload?: Record<string, unknown>;
}

export class DomainValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'DomainValidationError';
  }
}

export class CreacionDePedidoConTokenDeAutenticacionAggregate {
  private _state: CreacionDePedidoConTokenDeAutenticacionState = 'PENDING';
  private _version = 0;
  private readonly _events: CreacionDePedidoConTokenDeAutenticacionDomainEvent[] = [];

  constructor(public readonly id: string) {
    if (!id || !id.trim()) throw new DomainValidationError('CreacionDePedidoConTokenDeAutenticacion id is required');
  }

  /** Rebuilds an aggregate from persisted state; no events are recorded. */
  static restore(id: string, state: CreacionDePedidoConTokenDeAutenticacionState, version: number): CreacionDePedidoConTokenDeAutenticacionAggregate {
    const aggregate = new CreacionDePedidoConTokenDeAutenticacionAggregate(id);
    aggregate._state = state;
    aggregate._version = version;
    return aggregate;
  }

  get state(): CreacionDePedidoConTokenDeAutenticacionState {
    return this._state;
  }

  get version(): number {
    return this._version;
  }

  /** Events recorded since the aggregate was loaded (to be saved via an outbox). */
  get pendingEvents(): readonly CreacionDePedidoConTokenDeAutenticacionDomainEvent[] {
    return this._events;
  }

  processCreacionDePedidoConTokenDeAutenticacion(command: CreacionDePedidoConTokenDeAutenticacionCommand): CreacionDePedidoConTokenDeAutenticacionDomainEvent {
    this.assertValid(command);
    return this.record('ProcessCreacionDePedidoConTokenDeAutenticacionCompleted', command.payload ?? {});
  }

  private assertValid(command: CreacionDePedidoConTokenDeAutenticacionCommand): void {
    if (!command || !command.id || !command.id.trim()) throw new DomainValidationError('Command id is required');
    if (command.id !== this.id) throw new DomainValidationError(`Command targets ${command.id}, not ${this.id}`);
  }

  private record(type: CreacionDePedidoConTokenDeAutenticacionEventType, payload: Record<string, unknown>): CreacionDePedidoConTokenDeAutenticacionDomainEvent {
    this._version += 1;
    const event: CreacionDePedidoConTokenDeAutenticacionDomainEvent = { type, aggregateId: this.id, version: this._version, occurredOn: new Date(), payload };
    this._events.push(event);
    return event;
  }
}
